
# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: night eighties
#header decoration
slideshow: true 
ribban_bg: false
particle_bg: true

# Site settings
SEOTitle: 编程|HEXO|NODEJS|C++|碎碎念
email: e-mail_address
description: "字节艺术家的日常"
keyword: ""

# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "INNOVATION IS KING!"
sidebar-avatar: /img/avatar/ironman.png      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- archive
- friends-blog
#- category
# widget behavior
## Archive
archives-img: /img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true

## Friends
friends: [
    {
        title: "ACE theme for Hexo",
        href: "http://www.sumoon.com"
    }
#    ,
#    {
#        title: "your blog",
#        href: "http://"
#    }
]

#sticky post tag
sticky_tag: "Sticky"

# Analytics settings
#Baidu Analytics
ba_track_id: xxx
# Google Analytics
ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite


# SNS settings
# SNS Share
# Reference: https://github.com/overtrue/share.js
share: true
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    kinggozhang
# twitter_username:   Demonbane_x
# facebook_username:  xxx
# linkedin_username:  xxx
# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
#disqus_username: your-disqus-ID

